<a href="https://colab.research.google.com/github/ashhyyyy-vis/sEMG_ML/blob/main/ML_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.svm import SVC


In [ ]:
df=pd.read_csv('/content/emg_features_rms_mav_wl.csv')
pf=pd.read_csv('/content/emg_features_rms_mav_wl_var.csv')

In [ ]:
df.shape

(2625, 28)

In [ ]:
feature_cols = [col for col in df.columns if col.startswith("ch")]
X = df[feature_cols]
x=pf[feature_cols]
X.shape

(2625, 24)

In [ ]:
y = df["gesture"]
Y=pf["gesture"]
y.shape

(2625,)

In [ ]:
subjects = df["subject"]
SUBJECTS = pf["subject"]
subjects.shape

(2625,)

In [ ]:
scaler = StandardScaler()


In [ ]:

train_subjects = list(range(1, 21))
test_subjects  = list(range(21, 26))
train_mask = subjects.isin(train_subjects)
test_mask  = subjects.isin(test_subjects)
X_train = X[train_mask]
X_test  = X[test_mask]

x_train = x[train_mask]
x_test  = x[test_mask]

y_train = y[train_mask]
y_test  = y[test_mask]

Y_train = Y[train_mask]
Y_test  = Y[test_mask]



In [ ]:
print(X_train.shape)
print(X_test.shape)
print(y_train.value_counts())
print(y_test.value_counts())


(2100, 24)
(525, 24)
gesture
0    420
1    420
2    420
3    420
4    420
Name: count, dtype: int64
gesture
0    105
1    105
2    105
3    105
4    105
Name: count, dtype: int64


In [ ]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled  = scaler.transform(x_test)


In [ ]:
knn = KNeighborsClassifier(
    n_neighbors=5,
    metric="euclidean"
)


In [ ]:
knn.fit(X_train_scaled, y_train)
y_pred = knn.predict(X_test_scaled)
acc = accuracy_score(y_test, y_pred)
print("Test accuracy:", acc)
cm = confusion_matrix(y_test, y_pred)
print(cm)


Test accuracy: 0.5733333333333334
[[64 16 12 13  0]
 [ 1 59 38  7  0]
 [ 9 39 55  2  0]
 [28 17 14 45  1]
 [ 5  5  4 13 78]]


In [ ]:
knn.fit(x_train_scaled, Y_train)
Y_pred = knn.predict(x_test_scaled)
acc = accuracy_score(Y_test, Y_pred)
print("Test accuracy:", acc)
cm = confusion_matrix(Y_test, Y_pred)
print(cm)


Test accuracy: 0.5733333333333334
[[64 16 12 13  0]
 [ 1 59 38  7  0]
 [ 9 39 55  2  0]
 [28 17 14 45  1]
 [ 5  5  4 13 78]]


In [ ]:
svm = SVC(
    kernel="rbf",
    C=10,
    gamma=0.1
)


In [ ]:
svm.fit(X_train_scaled, y_train)
y_pred_svm = svm.predict(X_test_scaled)


In [ ]:
svm_acc = accuracy_score(y_test, y_pred_svm)
print("SVM Test accuracy:", svm_acc)


SVM Test accuracy: 0.6761904761904762


In [ ]:
cm_svm = confusion_matrix(y_test, y_pred_svm)
print(cm_svm)


[[76  9  0 20  0]
 [ 4 66 20 15  0]
 [11 26 66  2  0]
 [25 19  5 56  0]
 [ 3  3  0  8 91]]


In [ ]:
svm.fit(x_train_scaled, Y_train)
Y_pred_svm = svm.predict(x_test_scaled)


In [ ]:
svm_acc = accuracy_score(Y_test, Y_pred_svm)
print("SVM Test accuracy:", svm_acc)


SVM Test accuracy: 0.6761904761904762


In [ ]:
cm_svm = confusion_matrix(y_test, y_pred_svm)
print(cm_svm)

[[76  9  0 20  0]
 [ 4 66 20 15  0]
 [11 26 66  2  0]
 [25 19  5 56  0]
 [ 3  3  0  8 91]]
